version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - "${MONGOD_PORT}:27017"
    restart: always
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"

volumes:
  db-data:
